language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - android-22
    - add-on
    - extra

script: echo $TRAVIS_COMMIT $TRAVIS_REPO_SLUG 

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: "popcorn-builds"
  local_dir: app/build/outputs
  skip_cleanup: true

script: ./gradlew assemble
