language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - android-22
    - add-on
    - extra
    
addons:
    artifacts: true
    s3_region: "Oregon"
    ARTIFACTS_KEY=$aws_access
    ARTIFACTS_SECRET=$aws_secret
    ARTIFACTS_BUCKET=popcorn-builds
    paths:
    - $HOME/Popcorn/app/build/outputs/apk/app-debug.apk

script: ./gradlew assemble
