language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - android-22
    - add-on
    - extra

script:
  - ./gradlew assemble
  - BUCKET=${TRAVIS_REPO_SLUG%/*}
  - DIR=${TRAVIS_REPO_SLUG##*/}
  - echo $BUCKET $DIR $TRAVIS_COMMIT $TRAVIS_REPO_SLUG

before_deploy:
  - mv app/build/outputs/apk app/build/outputs/$DIR
  
deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $BUCKET/$DIR
  local_dir: app/build/outputs/$DIR
  skip_cleanup: true
