language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - android-22
    - add-on
    - extra
    
deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: "popcorn-builds"
  #local_dir: app/build/outputs

script: ./gradlew assemble

after_script: find /home/travis/build/gkiko/Popcorn/app/build/outputs
